[workspace]
members = [
  "ForgeANN",
  "cmd_drivers/build_forgeann_index",
  "cmd_drivers/search_mem_index",
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units=1
lto = true
overflow-checks = false

[workspace.dependencies]
monoio = { git = "https://github.com/bytedance/monoio" }
# monoio = { version = "0.2" }
io-uring = "0.6"
