[package]
name = "search_mem_index"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeann = { path = "../../ForgeANN", features = ["full_precision"] }
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
byteorder = "1.5"
bytemuck = "1.13"
anyhow = "1"
memmap2 = "0.5"
